# -*- coding: utf-8 -*-
"""fake_news.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdIn6XRYObqKU_ksK1IizKlC-DrPBFsn
"""

# import Libraries
import re
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


def clear_title(title):
    """Clean the input title before prediction."""
    title = str(title).lower()
    title = re.sub(r"\n", " ", title)
    return title.strip()


def load_data(fake_path="fake.csv.zip", true_path="true.csv.zip"):
    fake = pd.read_csv(fake_path)
    true = pd.read_csv(true_path)

    fake["class"] = 0
    true["class"] = 1

    data = pd.concat([fake, true], axis=0, ignore_index=True)
    data = data.drop(columns=[col for col in ["text", "subject", "date"] if col in data.columns])
    data["title"] = data["title"].apply(clear_title)
    return data


def train_and_save(fake_path="fake.csv.zip", true_path="true.csv.zip"):
    data = load_data(fake_path, true_path)
    x = data["title"]
    y = data["class"]

    xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state=42)

    vectorizer = TfidfVectorizer()
    xv_train = vectorizer.fit_transform(xtrain)
    xv_test = vectorizer.transform(xtest)

    model = LogisticRegression(max_iter=1000)
    model.fit(xv_train, ytrain)

    predict = model.predict(xv_test)
    print("Model Accuracy:", model.score(xv_test, ytest))
    print(classification_report(ytest, predict))

    joblib.dump(vectorizer, "vectorize.joblib")
    joblib.dump(model, "model.joblib")
    print("Saved vectorize.joblib and model.joblib")


if __name__ == "__main__":
    train_and_save()
